package builtin

import (
	"fmt"

	"github.com/tuipcli/tuip/internal/fetch"
	"github.com/tuipcli/tuip/internal/providers"
	"github.com/tuipcli/tuip/internal/providers/cloudflare"
	"github.com/tuipcli/tuip/internal/providers/github"
	"github.com/tuipcli/tuip/internal/providers/slack"
	"github.com/tuipcli/tuip/internal/providers/statuspage"
)

const coreProviderCount = 7

type registration struct {
	metadata providers.Metadata
	factory  providers.Factory
}

// NewRegistry returns a registry populated with tuip's built-in providers.
func NewRegistry(client *fetch.Client) (*providers.Registry, error) {
	registry := providers.NewRegistry()

	statuspageRegs := statuspageRegistrations(client)
	registrations := make([]registration, 0, coreProviderCount+len(statuspageRegs))
	registrations = append(registrations,
		registration{
			metadata: slack.New(client).Metadata(),
			factory:  func() providers.Provider { return slack.New(client) },
		},
		registration{
			metadata: github.New(client).Metadata(),
			factory:  func() providers.Provider { return github.New(client) },
		},
		registration{
			metadata: github.NewEnterpriseCloudAU(client).Metadata(),
			factory:  func() providers.Provider { return github.NewEnterpriseCloudAU(client) },
		},
		registration{
			metadata: github.NewEnterpriseCloudEU(client).Metadata(),
			factory:  func() providers.Provider { return github.NewEnterpriseCloudEU(client) },
		},
		registration{
			metadata: github.NewEnterpriseCloudJP(client).Metadata(),
			factory:  func() providers.Provider { return github.NewEnterpriseCloudJP(client) },
		},
		registration{
			metadata: github.NewEnterpriseCloudUS(client).Metadata(),
			factory:  func() providers.Provider { return github.NewEnterpriseCloudUS(client) },
		},
		registration{
			metadata: cloudflare.New(client).Metadata(),
			factory:  func() providers.Provider { return cloudflare.New(client) },
		},
	)

	registrations = append(registrations, statuspageRegs...)

	for _, registration := range registrations {
		err := registry.Register(registration.metadata, registration.factory)
		if err != nil {
			return nil, fmt.Errorf("register provider %s: %w", registration.metadata.ID, err)
		}
	}

	return registry, nil
}

func statuspageRegistrations(client *fetch.Client) []registration {
	options := []statuspage.Options{
		{
			ID:          "accelo",
			Name:        "Accelo",
			Description: "Accelo service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.accelo.com/",
			APIURL:      "https://status.accelo.com/api",
			SummaryURL:  "https://status.accelo.com/api/v2/summary.json",
		},
		{
			ID:          "affinity",
			Name:        "Affinity",
			Description: "Affinity service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.affinity.co/",
			APIURL:      "https://status.affinity.co/api",
			SummaryURL:  "https://status.affinity.co/api/v2/summary.json",
		},
		{
			ID:          "capsule",
			Aliases:     []string{"capsulecrm"},
			Name:        "Capsule",
			Description: "Capsule CRM service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.capsulecrm.com/",
			APIURL:      "https://status.capsulecrm.com/api",
			SummaryURL:  "https://status.capsulecrm.com/api/v2/summary.json",
		},
		{
			ID:          "hubspot",
			Name:        "HubSpot",
			Description: "HubSpot service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.hubspot.com/",
			APIURL:      "https://status.hubspot.com/api",
			SummaryURL:  "https://status.hubspot.com/api/v2/summary.json",
		},
		{
			ID:          "nutshell",
			Name:        "Nutshell",
			Description: "Nutshell service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.nutshell.com/",
			APIURL:      "https://status.nutshell.com/api",
			SummaryURL:  "https://status.nutshell.com/api/v2/summary.json",
		},
		{
			ID:          "monday",
			Aliases:     []string{"monday.com"},
			Name:        "monday.com",
			Description: "monday.com service status",
			Category:    "Project Management",
			SourceURL:   "https://status.monday.com/",
			APIURL:      "https://status.monday.com/api",
			SummaryURL:  "https://status.monday.com/api/v2/summary.json",
		},
		{
			ID:          "gusto",
			Name:        "Gusto",
			Description: "Gusto service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.gusto.com/",
			APIURL:      "https://status.gusto.com/api",
			SummaryURL:  "https://status.gusto.com/api/v2/summary.json",
		},
		{
			ID:          "officient",
			Aliases:     []string{"exact"},
			Name:        "Officient",
			Description: "Officient/Exact HR service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.officient.io/",
			APIURL:      "https://status.officient.io/api",
			SummaryURL:  "https://status.officient.io/api/v2/summary.json",
		},
		{
			ID:          "ashby",
			Aliases:     []string{"ashbyhq"},
			Name:        "Ashby",
			Description: "Ashby service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.ashbyhq.com/",
			APIURL:      "https://status.ashbyhq.com/api",
			SummaryURL:  "https://status.ashbyhq.com/api/v2/summary.json",
		},
		{
			ID:          "greenhouse",
			Name:        "Greenhouse",
			Description: "Greenhouse service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.greenhouse.io/",
			APIURL:      "https://status.greenhouse.io/api",
			SummaryURL:  "https://status.greenhouse.io/api/v2/summary.json",
		},
		{
			ID:          "workable",
			Name:        "Workable",
			Description: "Workable service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://workable.statuspage.io/",
			APIURL:      "https://workable.statuspage.io/api",
			SummaryURL:  "https://workable.statuspage.io/api/v2/summary.json",
		},
		{
			ID:          "freshbooks",
			Name:        "FreshBooks",
			Description: "FreshBooks service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.freshbooks.com/",
			APIURL:      "https://status.freshbooks.com/api",
			SummaryURL:  "https://status.freshbooks.com/api/v2/summary.json",
		},
		{
			ID:          "quickbooks-online",
			Aliases:     []string{"quickbooks", "qbo"},
			Name:        "QuickBooks Online",
			Description: "QuickBooks Online service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.quickbooks.intuit.com/",
			APIURL:      "https://status.quickbooks.intuit.com/api",
			SummaryURL:  "https://status.quickbooks.intuit.com/api/v2/summary.json",
		},
		{
			ID:          "xero",
			Name:        "Xero",
			Description: "Xero service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.xero.com/",
			APIURL:      "https://status.xero.com/api",
			SummaryURL:  "https://status.xero.com/api/v2/summary.json",
		},
		{
			ID:          "box",
			Name:        "Box",
			Description: "Box service status",
			Category:    "File Storage",
			SourceURL:   "https://status.box.com/",
			APIURL:      "https://status.box.com/api",
			SummaryURL:  "https://status.box.com/api/v2/summary.json",
		},
		{
			ID:          "dropbox",
			Name:        "Dropbox",
			Description: "Dropbox service status",
			Category:    "File Storage",
			SourceURL:   "https://status.dropbox.com/",
			APIURL:      "https://status.dropbox.com/api",
			SummaryURL:  "https://status.dropbox.com/api/v2/summary.json",
		},
		{
			ID:          "asana",
			Name:        "Asana",
			Description: "Asana service status",
			Category:    "Project Management",
			SourceURL:   "https://status.asana.com/",
			APIURL:      "https://status.asana.com/api",
			SummaryURL:  "https://status.asana.com/api/v2/summary.json",
		},
		{
			ID:          "bitbucket",
			Name:        "Bitbucket",
			Description: "Atlassian Bitbucket service status",
			Category:    "Developer Tools",
			SourceURL:   "https://bitbucket.status.atlassian.com/",
			APIURL:      "https://bitbucket.status.atlassian.com/api",
			SummaryURL:  "https://bitbucket.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "hive",
			Name:        "Hive",
			Description: "Hive service status",
			Category:    "Project Management",
			SourceURL:   "https://status.hive.com/",
			APIURL:      "https://status.hive.com/api",
			SummaryURL:  "https://status.hive.com/api/v2/summary.json",
		},
		{
			ID:          "jira",
			Aliases:     []string{"jira-software"},
			Name:        "Jira",
			Description: "Jira service status",
			Category:    "Project Management",
			SourceURL:   "https://jira-software.status.atlassian.com/",
			APIURL:      "https://jira-software.status.atlassian.com/api",
			SummaryURL:  "https://jira-software.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "trello",
			Name:        "Trello",
			Description: "Trello service status",
			Category:    "Project Management",
			SourceURL:   "https://trello.status.atlassian.com/",
			APIURL:      "https://trello.status.atlassian.com/api",
			SummaryURL:  "https://trello.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "confluence",
			Name:        "Confluence",
			Description: "Confluence service status",
			Category:    "Collaboration",
			SourceURL:   "https://confluence.status.atlassian.com/",
			APIURL:      "https://confluence.status.atlassian.com/api",
			SummaryURL:  "https://confluence.status.atlassian.com/api/v2/summary.json",
		},
		// Data, cloud, AI, and observability providers.
		{
			ID:          "sigma",
			Aliases:     []string{"sigma-computing"},
			Name:        "Sigma Computing",
			Description: "Sigma Computing service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.sigmacomputing.com/",
			APIURL:      "https://status.sigmacomputing.com/api",
			SummaryURL:  "https://status.sigmacomputing.com/api/v2/summary.json",
		},
		{
			ID:          "hex",
			Name:        "Hex",
			Description: "Hex service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.hex.tech/",
			APIURL:      "https://status.hex.tech/api",
			SummaryURL:  "https://status.hex.tech/api/v2/summary.json",
		},
		{
			ID:          "metabase-cloud",
			Aliases:     []string{"metabase"},
			Name:        "Metabase Cloud",
			Description: "Metabase Cloud service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.metabase.com/",
			APIURL:      "https://status.metabase.com/api",
			SummaryURL:  "https://status.metabase.com/api/v2/summary.json",
		},
		{
			ID:          "omni",
			Aliases:     []string{"omni-analytics"},
			Name:        "Omni Analytics",
			Description: "Omni Analytics service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.omni.co/",
			APIURL:      "https://status.omni.co/api",
			SummaryURL:  "https://status.omni.co/api/v2/summary.json",
		},
		{
			ID:          "preset",
			Aliases:     []string{"preset-cloud"},
			Name:        "Preset",
			Description: "Preset service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.preset.io/",
			APIURL:      "https://status.preset.io/api/v2/summary.json",
			SummaryURL:  "https://status.preset.io/api/v2/summary.json",
		},
		{
			ID:          "fivetran",
			Name:        "Fivetran",
			Description: "Fivetran service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.fivetran.com/",
			APIURL:      "https://status.fivetran.com/api",
			SummaryURL:  "https://status.fivetran.com/api/v2/summary.json",
		},
		{
			ID:          "hevo",
			Aliases:     []string{"hevo-data"},
			Name:        "Hevo",
			Description: "Hevo service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.hevodata.com/",
			APIURL:      "https://status.hevodata.com/api",
			SummaryURL:  "https://status.hevodata.com/api/v2/summary.json",
		},
		{
			ID:          "matillion",
			Name:        "Matillion",
			Description: "Matillion service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.matillion.com/",
			APIURL:      "https://status.matillion.com/api",
			SummaryURL:  "https://status.matillion.com/api/v2/summary.json",
		},
		{
			ID:          "astronomer",
			Aliases:     []string{"astro"},
			Name:        "Astronomer Astro",
			Description: "Astronomer Astro service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.astronomer.io/",
			APIURL:      "https://status.astronomer.io/api",
			SummaryURL:  "https://status.astronomer.io/api/v2/summary.json",
		},
		{
			ID:          "atlan",
			Name:        "Atlan",
			Description: "Atlan service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.atlan.com/",
			APIURL:      "https://status.atlan.com/api/v2/summary.json",
			SummaryURL:  "https://status.atlan.com/api/v2/summary.json",
		},
		{
			ID:          "clickhouse-cloud",
			Aliases:     []string{"clickhouse"},
			Name:        "ClickHouse Cloud",
			Description: "ClickHouse Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.clickhouse.com/",
			APIURL:      "https://status.clickhouse.com/api/v2/summary.json",
			SummaryURL:  "https://status.clickhouse.com/api/v2/summary.json",
		},
		{
			ID:          "confluent-cloud",
			Aliases:     []string{"confluent"},
			Name:        "Confluent Cloud",
			Description: "Confluent Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.confluent.cloud/",
			APIURL:      "https://status.confluent.cloud/api",
			SummaryURL:  "https://status.confluent.cloud/api/v2/summary.json",
		},
		{
			ID:          "dbt-cloud",
			Aliases:     []string{"dbt", "getdbt"},
			Name:        "dbt Cloud",
			Description: "dbt Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.getdbt.com/",
			APIURL:      "https://status.getdbt.com/api/v2/summary.json",
			SummaryURL:  "https://status.getdbt.com/api/v2/summary.json",
		},
		{
			ID:          "dremio-cloud",
			Aliases:     []string{"dremio"},
			Name:        "Dremio Cloud",
			Description: "Dremio Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.dremio.com/",
			APIURL:      "https://status.dremio.com/api",
			SummaryURL:  "https://status.dremio.com/api/v2/summary.json",
		},
		{
			ID:          "snowflake",
			Name:        "Snowflake",
			Description: "Snowflake service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.snowflake.com/",
			APIURL:      "https://status.snowflake.com/api",
			SummaryURL:  "https://status.snowflake.com/api/v2/summary.json",
		},
		{
			ID:          "aiven",
			Name:        "Aiven",
			Description: "Aiven service status",
			Category:    "Databases",
			SourceURL:   "https://status.aiven.io/",
			APIURL:      "https://status.aiven.io/api/v2/summary.json",
			SummaryURL:  "https://status.aiven.io/api/v2/summary.json",
		},
		{
			ID:          "elastic-cloud",
			Aliases:     []string{"elastic"},
			Name:        "Elastic Cloud",
			Description: "Elastic Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.elastic.co/",
			APIURL:      "https://status.elastic.co/api",
			SummaryURL:  "https://status.elastic.co/api/v2/summary.json",
		},
		{
			ID:          "mongodb-cloud",
			Aliases:     []string{"mongodb", "mongodb-atlas", "atlas"},
			Name:        "MongoDB Cloud",
			Description: "MongoDB Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.cloud.mongodb.com/",
			APIURL:      "https://status.cloud.mongodb.com/api",
			SummaryURL:  "https://status.cloud.mongodb.com/api/v2/summary.json",
		},
		{
			ID:          "pinecone",
			Name:        "Pinecone",
			Description: "Pinecone service status",
			Category:    "Databases",
			SourceURL:   "https://status.pinecone.io/",
			APIURL:      "https://status.pinecone.io/api",
			SummaryURL:  "https://status.pinecone.io/api/v2/summary.json",
		},
		{
			ID:          "planetscale",
			Name:        "PlanetScale",
			Description: "PlanetScale service status",
			Category:    "Databases",
			SourceURL:   "https://www.planetscalestatus.com/",
			APIURL:      "https://www.planetscalestatus.com/api/v2/summary.json",
			SummaryURL:  "https://www.planetscalestatus.com/api/v2/summary.json",
		},
		{
			ID:          "supabase",
			Name:        "Supabase",
			Description: "Supabase service status",
			Category:    "Databases",
			SourceURL:   "https://status.supabase.com/",
			APIURL:      "https://status.supabase.com/api",
			SummaryURL:  "https://status.supabase.com/api/v2/summary.json",
		},
		{
			ID:          "zilliz",
			Aliases:     []string{"zilliz-cloud"},
			Name:        "Zilliz Cloud",
			Description: "Zilliz Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.zilliz.com/",
			APIURL:      "https://status.zilliz.com/api",
			SummaryURL:  "https://status.zilliz.com/api/v2/summary.json",
		},
		{
			ID:          "digitalocean",
			Aliases:     []string{"do"},
			Name:        "DigitalOcean",
			Description: "DigitalOcean service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.digitalocean.com/",
			APIURL:      "https://status.digitalocean.com/api",
			SummaryURL:  "https://status.digitalocean.com/api/v2/summary.json",
		},
		{
			ID:          "fly",
			Aliases:     []string{"fly.io", "flyio"},
			Name:        "Fly.io",
			Description: "Fly.io service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.flyio.net/",
			APIURL:      "https://status.flyio.net/api",
			SummaryURL:  "https://status.flyio.net/api/v2/summary.json",
		},
		{
			ID:          "netlify",
			Name:        "Netlify",
			Description: "Netlify service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://www.netlifystatus.com/",
			APIURL:      "https://www.netlifystatus.com/api",
			SummaryURL:  "https://www.netlifystatus.com/api/v2/summary.json",
		},
		{
			ID:          "render",
			Name:        "Render",
			Description: "Render service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.render.com/",
			APIURL:      "https://status.render.com/api",
			SummaryURL:  "https://status.render.com/api/v2/summary.json",
		},
		{
			ID:          "vercel",
			Name:        "Vercel",
			Description: "Vercel service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://www.vercel-status.com/",
			APIURL:      "https://www.vercel-status.com/api",
			SummaryURL:  "https://www.vercel-status.com/api/v2/summary.json",
		},
		{
			ID:          "anthropic",
			Aliases:     []string{"claude"},
			Name:        "Anthropic",
			Description: "Anthropic Claude service status",
			Category:    "AI",
			SourceURL:   "https://status.anthropic.com/",
			APIURL:      "https://status.anthropic.com/api",
			SummaryURL:  "https://status.anthropic.com/api/v2/summary.json",
		},
		{
			ID:          "openai",
			Aliases:     []string{"chatgpt"},
			Name:        "OpenAI",
			Description: "OpenAI service status",
			Category:    "AI",
			SourceURL:   "https://status.openai.com/",
			APIURL:      "https://status.openai.com/api/v2/summary.json",
			SummaryURL:  "https://status.openai.com/api/v2/summary.json",
		},
		{
			ID:          "bigeye",
			Name:        "Bigeye",
			Description: "Bigeye service status",
			Category:    "Observability",
			SourceURL:   "https://status.bigeye.com/",
			APIURL:      "https://status.bigeye.com/api",
			SummaryURL:  "https://status.bigeye.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-us1",
			Aliases:     []string{"datadog"},
			Name:        "Datadog US1",
			Description: "Datadog US1 service status",
			Category:    "Observability",
			SourceURL:   "https://status.datadoghq.com/",
			APIURL:      "https://status.datadoghq.com/api",
			SummaryURL:  "https://status.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-eu",
			Aliases:     []string{"ddog-eu"},
			Name:        "Datadog EU",
			Description: "Datadog EU service status",
			Category:    "Observability",
			SourceURL:   "https://status.datadoghq.eu/",
			APIURL:      "https://status.datadoghq.eu/api",
			SummaryURL:  "https://status.datadoghq.eu/api/v2/summary.json",
		},
		{
			ID:          "datadog-us5",
			Aliases:     []string{"ddog-us5"},
			Name:        "Datadog US5",
			Description: "Datadog US5 service status",
			Category:    "Observability",
			SourceURL:   "https://status.us5.datadoghq.com/",
			APIURL:      "https://status.us5.datadoghq.com/api",
			SummaryURL:  "https://status.us5.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-ap1",
			Aliases:     []string{"ddog-ap1"},
			Name:        "Datadog AP1",
			Description: "Datadog AP1 service status",
			Category:    "Observability",
			SourceURL:   "https://status.ap1.datadoghq.com/",
			APIURL:      "https://status.ap1.datadoghq.com/api",
			SummaryURL:  "https://status.ap1.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-ap2",
			Aliases:     []string{"ddog-ap2"},
			Name:        "Datadog AP2",
			Description: "Datadog AP2 service status",
			Category:    "Observability",
			SourceURL:   "https://status.ap2.datadoghq.com/",
			APIURL:      "https://status.ap2.datadoghq.com/api",
			SummaryURL:  "https://status.ap2.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-govcloud",
			Aliases:     []string{"datadog-gov", "ddog-gov", "ddog-govcloud"},
			Name:        "Datadog GovCloud",
			Description: "Datadog GovCloud service status",
			Category:    "Observability",
			SourceURL:   "https://status.ddog-gov.com/",
			APIURL:      "https://status.ddog-gov.com/api",
			SummaryURL:  "https://status.ddog-gov.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-us2-gov",
			Aliases:     []string{"ddog-us2-gov", "datadog-us2-fed", "ddog-us2-fed"},
			Name:        "Datadog US2 Gov",
			Description: "Datadog US2 Gov service status",
			Category:    "Observability",
			SourceURL:   "https://status.us2.ddog-gov.com/",
			APIURL:      "https://status.us2.ddog-gov.com/api",
			SummaryURL:  "https://status.us2.ddog-gov.com/api/v2/summary.json",
		},
		{
			ID:          "new-relic",
			Aliases:     []string{"newrelic"},
			Name:        "New Relic",
			Description: "New Relic service status",
			Category:    "Observability",
			SourceURL:   "https://status.newrelic.com/",
			APIURL:      "https://status.newrelic.com/api",
			SummaryURL:  "https://status.newrelic.com/api/v2/summary.json",
		},
		{
			ID:          "sentry",
			Name:        "Sentry",
			Description: "Sentry service status",
			Category:    "Observability",
			SourceURL:   "https://status.sentry.io/",
			APIURL:      "https://status.sentry.io/api",
			SummaryURL:  "https://status.sentry.io/api/v2/summary.json",
		},
		{
			ID:          "twilio",
			Name:        "Twilio",
			Description: "Twilio service status",
			Category:    "Communication",
			SourceURL:   "https://status.twilio.com/",
			APIURL:      "https://status.twilio.com/api",
			SummaryURL:  "https://status.twilio.com/api/v2/summary.json",
		},
	}

	registrations := make([]registration, 0, len(options))
	for _, option := range options {
		current := option
		provider := statuspage.NewProvider(client, current)
		registrations = append(registrations, registration{
			metadata: provider.Metadata(),
			factory: func() providers.Provider {
				return statuspage.NewProvider(client, current)
			},
		})
	}

	return registrations
}
