package builtin

import (
	"fmt"

	"github.com/ikan31/tuip/internal/fetch"
	"github.com/ikan31/tuip/internal/providers"
	"github.com/ikan31/tuip/internal/providers/pagerdutystatus"
	"github.com/ikan31/tuip/internal/providers/slack"
	"github.com/ikan31/tuip/internal/providers/statuspage"
	"github.com/ikan31/tuip/internal/providers/uptimekuma"
)

const customProviderCount = 1

type registration struct {
	metadata providers.Metadata
	factory  providers.Factory
}

// NewRegistry returns a registry populated with tuip's built-in providers.
func NewRegistry(client *fetch.Client) (*providers.Registry, error) {
	registry := providers.NewRegistry()

	statuspageRegs := statuspageRegistrations(client)
	pagerDutyStatusRegs := pagerDutyStatusRegistrations(client)
	uptimeKumaRegs := uptimeKumaRegistrations(client)
	registrations := make([]registration, 0, customProviderCount+len(pagerDutyStatusRegs)+len(uptimeKumaRegs)+len(statuspageRegs))
	registrations = append(registrations, registration{
		metadata: slack.New(client).Metadata(),
		factory:  func() providers.Provider { return slack.New(client) },
	})

	registrations = append(registrations, pagerDutyStatusRegs...)
	registrations = append(registrations, uptimeKumaRegs...)
	registrations = append(registrations, statuspageRegs...)

	for _, registration := range registrations {
		err := registry.Register(registration.metadata, registration.factory)
		if err != nil {
			return nil, fmt.Errorf("register provider %s: %w", registration.metadata.ID, err)
		}
	}

	return registry, nil
}

func pagerDutyStatusRegistrations(client *fetch.Client) []registration {
	options := []pagerdutystatus.Options{
		{
			ID:          "pagerduty",
			Name:        "PagerDuty",
			Description: "PagerDuty service status",
			Category:    "Incident Management",
			SourceURL:   "https://status.pagerduty.com/",
			APIURL:      "https://status.pagerduty.com/api/data",
			DataURL:     "https://status.pagerduty.com/api/data",
		},
		{
			ID:          "github-enterprise-cloud-au",
			Aliases:     []string{"github-au", "ghec-au"},
			Name:        "GitHub Enterprise Cloud - Australia",
			Description: "GitHub Enterprise Cloud Australia regional status",
			Category:    "Developer Tools",
			SourceURL:   "https://au.githubstatus.com/",
			APIURL:      "https://au.githubstatus.com/api/data",
			DataURL:     "https://au.githubstatus.com/api/data",
		},
		{
			ID:          "github-enterprise-cloud-jp",
			Aliases:     []string{"github-jp", "ghec-jp"},
			Name:        "GitHub Enterprise Cloud - Japan",
			Description: "GitHub Enterprise Cloud Japan regional status",
			Category:    "Developer Tools",
			SourceURL:   "https://jp.githubstatus.com/",
			APIURL:      "https://jp.githubstatus.com/api/data",
			DataURL:     "https://jp.githubstatus.com/api/data",
		},
		{
			ID:          "github-enterprise-cloud-us",
			Aliases:     []string{"github-us", "ghec-us"},
			Name:        "GitHub Enterprise Cloud - US",
			Description: "GitHub Enterprise Cloud US regional status",
			Category:    "Developer Tools",
			SourceURL:   "https://us.githubstatus.com/",
			APIURL:      "https://us.githubstatus.com/api/data",
			DataURL:     "https://us.githubstatus.com/api/data",
		},
		{
			ID:          "motherduck",
			Name:        "MotherDuck",
			Description: "MotherDuck service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.motherduck.com/posts/dashboard",
			APIURL:      "https://status.motherduck.com/api/data",
			DataURL:     "https://status.motherduck.com/api/data",
		},
	}

	registrations := make([]registration, 0, len(options))
	for _, option := range options {
		current := option
		provider := pagerdutystatus.NewProvider(client, current)
		registrations = append(registrations, registration{
			metadata: provider.Metadata(),
			factory: func() providers.Provider {
				return pagerdutystatus.NewProvider(client, current)
			},
		})
	}

	return registrations
}

func uptimeKumaRegistrations(client *fetch.Client) []registration {
	options := []uptimekuma.Options{
		{
			ID:           "codeberg",
			Name:         "Codeberg",
			Description:  "Codeberg service status",
			Category:     "Developer Tools",
			SourceURL:    "https://status.codeberg.org/status/codeberg",
			APIURL:       "https://status.codeberg.org/api/status-page/codeberg",
			StatusURL:    "https://status.codeberg.org/api/status-page/codeberg",
			HeartbeatURL: "https://status.codeberg.org/api/status-page/heartbeat/codeberg",
		},
		{
			ID:           "forgejo",
			Name:         "Forgejo",
			Description:  "Forgejo service status",
			Category:     "Developer Tools",
			SourceURL:    "https://status.forgejo.org/",
			APIURL:       "https://status.forgejo.org/api/status-page/forgejo",
			StatusURL:    "https://status.forgejo.org/api/status-page/forgejo",
			HeartbeatURL: "https://status.forgejo.org/api/status-page/heartbeat/forgejo",
		},
	}

	registrations := make([]registration, 0, len(options))
	for _, option := range options {
		current := option
		provider := uptimekuma.NewProvider(client, current)
		registrations = append(registrations, registration{
			metadata: provider.Metadata(),
			factory: func() providers.Provider {
				return uptimekuma.NewProvider(client, current)
			},
		})
	}

	return registrations
}

func statuspageRegistrations(client *fetch.Client) []registration {
	options := []statuspage.Options{
		{
			ID:          "cloudflare",
			Name:        "Cloudflare",
			Description: "Cloudflare service status",
			Category:    "Infrastructure",
			SourceURL:   "https://www.cloudflarestatus.com/",
			APIURL:      "https://www.cloudflarestatus.com/api",
			SummaryURL:  "https://www.cloudflarestatus.com/api/v2/summary.json",
		},
		{
			ID:          "github",
			Name:        "GitHub",
			Description: "GitHub service status",
			Category:    "Developer Tools",
			SourceURL:   "https://www.githubstatus.com/#",
			APIURL:      "https://www.githubstatus.com/api/v2/summary.json",
			SummaryURL:  "https://www.githubstatus.com/api/v2/summary.json",
		},
		{
			ID:          "github-enterprise-cloud-eu",
			Aliases:     []string{"github-eu", "ghec-eu"},
			Name:        "GitHub Enterprise Cloud - EU",
			Description: "GitHub Enterprise Cloud EU regional status",
			Category:    "Developer Tools",
			SourceURL:   "https://eu.githubstatus.com/",
			APIURL:      "https://eu.githubstatus.com/api/v2/summary.json",
			SummaryURL:  "https://eu.githubstatus.com/api/v2/summary.json",
		},
		{
			ID:          "accelo",
			Name:        "Accelo",
			Description: "Accelo service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.accelo.com/",
			APIURL:      "https://status.accelo.com/api",
			SummaryURL:  "https://status.accelo.com/api/v2/summary.json",
		},
		{
			ID:          "affinity",
			Name:        "Affinity",
			Description: "Affinity service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.affinity.co/",
			APIURL:      "https://status.affinity.co/api",
			SummaryURL:  "https://status.affinity.co/api/v2/summary.json",
		},
		{
			ID:          "capsule",
			Aliases:     []string{"capsulecrm"},
			Name:        "Capsule",
			Description: "Capsule CRM service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.capsulecrm.com/",
			APIURL:      "https://status.capsulecrm.com/api",
			SummaryURL:  "https://status.capsulecrm.com/api/v2/summary.json",
		},
		{
			ID:          "hubspot",
			Name:        "HubSpot",
			Description: "HubSpot service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.hubspot.com/",
			APIURL:      "https://status.hubspot.com/api",
			SummaryURL:  "https://status.hubspot.com/api/v2/summary.json",
		},
		{
			ID:          "nutshell",
			Name:        "Nutshell",
			Description: "Nutshell service status",
			Category:    "CRM & Sales",
			SourceURL:   "https://status.nutshell.com/",
			APIURL:      "https://status.nutshell.com/api",
			SummaryURL:  "https://status.nutshell.com/api/v2/summary.json",
		},
		{
			ID:          "monday",
			Aliases:     []string{"monday.com"},
			Name:        "monday.com",
			Description: "monday.com service status",
			Category:    "Project Management",
			SourceURL:   "https://status.monday.com/",
			APIURL:      "https://status.monday.com/api",
			SummaryURL:  "https://status.monday.com/api/v2/summary.json",
		},
		{
			ID:          "gusto",
			Name:        "Gusto",
			Description: "Gusto service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.gusto.com/",
			APIURL:      "https://status.gusto.com/api",
			SummaryURL:  "https://status.gusto.com/api/v2/summary.json",
		},
		{
			ID:          "officient",
			Aliases:     []string{"exact"},
			Name:        "Officient",
			Description: "Officient/Exact HR service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.officient.io/",
			APIURL:      "https://status.officient.io/api",
			SummaryURL:  "https://status.officient.io/api/v2/summary.json",
		},
		{
			ID:          "ashby",
			Aliases:     []string{"ashbyhq"},
			Name:        "Ashby",
			Description: "Ashby service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.ashbyhq.com/",
			APIURL:      "https://status.ashbyhq.com/api",
			SummaryURL:  "https://status.ashbyhq.com/api/v2/summary.json",
		},
		{
			ID:          "greenhouse",
			Name:        "Greenhouse",
			Description: "Greenhouse service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://status.greenhouse.io/",
			APIURL:      "https://status.greenhouse.io/api",
			SummaryURL:  "https://status.greenhouse.io/api/v2/summary.json",
		},
		{
			ID:          "workable",
			Name:        "Workable",
			Description: "Workable service status",
			Category:    "HR & Workforce",
			SourceURL:   "https://workable.statuspage.io/",
			APIURL:      "https://workable.statuspage.io/api",
			SummaryURL:  "https://workable.statuspage.io/api/v2/summary.json",
		},
		{
			ID:          "freshbooks",
			Name:        "FreshBooks",
			Description: "FreshBooks service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.freshbooks.com/",
			APIURL:      "https://status.freshbooks.com/api",
			SummaryURL:  "https://status.freshbooks.com/api/v2/summary.json",
		},
		{
			ID:          "quickbooks-online",
			Aliases:     []string{"quickbooks", "qbo"},
			Name:        "QuickBooks Online",
			Description: "QuickBooks Online service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.quickbooks.intuit.com/",
			APIURL:      "https://status.quickbooks.intuit.com/api",
			SummaryURL:  "https://status.quickbooks.intuit.com/api/v2/summary.json",
		},
		{
			ID:          "xero",
			Name:        "Xero",
			Description: "Xero service status",
			Category:    "Finance & Accounting",
			SourceURL:   "https://status.xero.com/",
			APIURL:      "https://status.xero.com/api",
			SummaryURL:  "https://status.xero.com/api/v2/summary.json",
		},
		{
			ID:          "box",
			Name:        "Box",
			Description: "Box service status",
			Category:    "File Storage",
			SourceURL:   "https://status.box.com/",
			APIURL:      "https://status.box.com/api",
			SummaryURL:  "https://status.box.com/api/v2/summary.json",
		},
		{
			ID:          "dropbox",
			Name:        "Dropbox",
			Description: "Dropbox service status",
			Category:    "File Storage",
			SourceURL:   "https://status.dropbox.com/",
			APIURL:      "https://status.dropbox.com/api",
			SummaryURL:  "https://status.dropbox.com/api/v2/summary.json",
		},
		{
			ID:          "asana",
			Name:        "Asana",
			Description: "Asana service status",
			Category:    "Project Management",
			SourceURL:   "https://status.asana.com/",
			APIURL:      "https://status.asana.com/api",
			SummaryURL:  "https://status.asana.com/api/v2/summary.json",
		},
		{
			ID:          "bitbucket",
			Name:        "Bitbucket",
			Description: "Atlassian Bitbucket service status",
			Category:    "Developer Tools",
			SourceURL:   "https://bitbucket.status.atlassian.com/",
			APIURL:      "https://bitbucket.status.atlassian.com/api",
			SummaryURL:  "https://bitbucket.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "hive",
			Name:        "Hive",
			Description: "Hive service status",
			Category:    "Project Management",
			SourceURL:   "https://status.hive.com/",
			APIURL:      "https://status.hive.com/api",
			SummaryURL:  "https://status.hive.com/api/v2/summary.json",
		},
		{
			ID:          "jira",
			Aliases:     []string{"jira-software"},
			Name:        "Jira",
			Description: "Jira service status",
			Category:    "Project Management",
			SourceURL:   "https://jira-software.status.atlassian.com/",
			APIURL:      "https://jira-software.status.atlassian.com/api",
			SummaryURL:  "https://jira-software.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "trello",
			Name:        "Trello",
			Description: "Trello service status",
			Category:    "Project Management",
			SourceURL:   "https://trello.status.atlassian.com/",
			APIURL:      "https://trello.status.atlassian.com/api",
			SummaryURL:  "https://trello.status.atlassian.com/api/v2/summary.json",
		},
		{
			ID:          "confluence",
			Name:        "Confluence",
			Description: "Confluence service status",
			Category:    "Collaboration",
			SourceURL:   "https://confluence.status.atlassian.com/",
			APIURL:      "https://confluence.status.atlassian.com/api",
			SummaryURL:  "https://confluence.status.atlassian.com/api/v2/summary.json",
		},
		// Data, cloud, AI, and observability providers.
		{
			ID:          "sigma",
			Aliases:     []string{"sigma-computing"},
			Name:        "Sigma Computing",
			Description: "Sigma Computing service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.sigmacomputing.com/",
			APIURL:      "https://status.sigmacomputing.com/api",
			SummaryURL:  "https://status.sigmacomputing.com/api/v2/summary.json",
		},
		{
			ID:          "hex",
			Name:        "Hex",
			Description: "Hex service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.hex.tech/",
			APIURL:      "https://status.hex.tech/api",
			SummaryURL:  "https://status.hex.tech/api/v2/summary.json",
		},
		{
			ID:          "metabase-cloud",
			Aliases:     []string{"metabase"},
			Name:        "Metabase Cloud",
			Description: "Metabase Cloud service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.metabase.com/",
			APIURL:      "https://status.metabase.com/api",
			SummaryURL:  "https://status.metabase.com/api/v2/summary.json",
		},
		{
			ID:          "omni",
			Aliases:     []string{"omni-analytics"},
			Name:        "Omni Analytics",
			Description: "Omni Analytics service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.omni.co/",
			APIURL:      "https://status.omni.co/api",
			SummaryURL:  "https://status.omni.co/api/v2/summary.json",
		},
		{
			ID:          "preset",
			Aliases:     []string{"preset-cloud"},
			Name:        "Preset",
			Description: "Preset service status",
			Category:    "Analytics & BI",
			SourceURL:   "https://status.preset.io/",
			APIURL:      "https://status.preset.io/api/v2/summary.json",
			SummaryURL:  "https://status.preset.io/api/v2/summary.json",
		},
		{
			ID:          "fivetran",
			Name:        "Fivetran",
			Description: "Fivetran service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.fivetran.com/",
			APIURL:      "https://status.fivetran.com/api",
			SummaryURL:  "https://status.fivetran.com/api/v2/summary.json",
		},
		{
			ID:          "hevo",
			Aliases:     []string{"hevo-data"},
			Name:        "Hevo",
			Description: "Hevo service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.hevodata.com/",
			APIURL:      "https://status.hevodata.com/api",
			SummaryURL:  "https://status.hevodata.com/api/v2/summary.json",
		},
		{
			ID:          "matillion",
			Name:        "Matillion",
			Description: "Matillion service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.matillion.com/",
			APIURL:      "https://status.matillion.com/api",
			SummaryURL:  "https://status.matillion.com/api/v2/summary.json",
		},
		{
			ID:          "astronomer",
			Aliases:     []string{"astro"},
			Name:        "Astronomer Astro",
			Description: "Astronomer Astro service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.astronomer.io/",
			APIURL:      "https://status.astronomer.io/api",
			SummaryURL:  "https://status.astronomer.io/api/v2/summary.json",
		},
		{
			ID:          "atlan",
			Name:        "Atlan",
			Description: "Atlan service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.atlan.com/",
			APIURL:      "https://status.atlan.com/api/v2/summary.json",
			SummaryURL:  "https://status.atlan.com/api/v2/summary.json",
		},
		{
			ID:          "clickhouse-cloud",
			Aliases:     []string{"clickhouse"},
			Name:        "ClickHouse Cloud",
			Description: "ClickHouse Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.clickhouse.com/",
			APIURL:      "https://status.clickhouse.com/api/v2/summary.json",
			SummaryURL:  "https://status.clickhouse.com/api/v2/summary.json",
		},
		{
			ID:          "confluent-cloud",
			Aliases:     []string{"confluent"},
			Name:        "Confluent Cloud",
			Description: "Confluent Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.confluent.cloud/",
			APIURL:      "https://status.confluent.cloud/api",
			SummaryURL:  "https://status.confluent.cloud/api/v2/summary.json",
		},
		{
			ID:          "dbt-cloud",
			Aliases:     []string{"dbt", "getdbt"},
			Name:        "dbt Cloud",
			Description: "dbt Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.getdbt.com/",
			APIURL:      "https://status.getdbt.com/api/v2/summary.json",
			SummaryURL:  "https://status.getdbt.com/api/v2/summary.json",
		},
		{
			ID:          "dremio-cloud",
			Aliases:     []string{"dremio"},
			Name:        "Dremio Cloud",
			Description: "Dremio Cloud service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.dremio.com/",
			APIURL:      "https://status.dremio.com/api",
			SummaryURL:  "https://status.dremio.com/api/v2/summary.json",
		},
		{
			ID:          "snowflake",
			Name:        "Snowflake",
			Description: "Snowflake service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.snowflake.com/",
			APIURL:      "https://status.snowflake.com/api",
			SummaryURL:  "https://status.snowflake.com/api/v2/summary.json",
		},
		{
			ID:          "aiven",
			Name:        "Aiven",
			Description: "Aiven service status",
			Category:    "Databases",
			SourceURL:   "https://status.aiven.io/",
			APIURL:      "https://status.aiven.io/api/v2/summary.json",
			SummaryURL:  "https://status.aiven.io/api/v2/summary.json",
		},
		{
			ID:          "elastic-cloud",
			Aliases:     []string{"elastic"},
			Name:        "Elastic Cloud",
			Description: "Elastic Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.elastic.co/",
			APIURL:      "https://status.elastic.co/api",
			SummaryURL:  "https://status.elastic.co/api/v2/summary.json",
		},
		{
			ID:          "mongodb-cloud",
			Aliases:     []string{"mongodb", "mongodb-atlas", "atlas"},
			Name:        "MongoDB Cloud",
			Description: "MongoDB Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.cloud.mongodb.com/",
			APIURL:      "https://status.cloud.mongodb.com/api",
			SummaryURL:  "https://status.cloud.mongodb.com/api/v2/summary.json",
		},
		{
			ID:          "pinecone",
			Name:        "Pinecone",
			Description: "Pinecone service status",
			Category:    "Databases",
			SourceURL:   "https://status.pinecone.io/",
			APIURL:      "https://status.pinecone.io/api",
			SummaryURL:  "https://status.pinecone.io/api/v2/summary.json",
		},
		{
			ID:          "planetscale",
			Name:        "PlanetScale",
			Description: "PlanetScale service status",
			Category:    "Databases",
			SourceURL:   "https://www.planetscalestatus.com/",
			APIURL:      "https://www.planetscalestatus.com/api/v2/summary.json",
			SummaryURL:  "https://www.planetscalestatus.com/api/v2/summary.json",
		},
		{
			ID:          "supabase",
			Name:        "Supabase",
			Description: "Supabase service status",
			Category:    "Databases",
			SourceURL:   "https://status.supabase.com/",
			APIURL:      "https://status.supabase.com/api",
			SummaryURL:  "https://status.supabase.com/api/v2/summary.json",
		},
		{
			ID:          "zilliz",
			Aliases:     []string{"zilliz-cloud"},
			Name:        "Zilliz Cloud",
			Description: "Zilliz Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.zilliz.com/",
			APIURL:      "https://status.zilliz.com/api",
			SummaryURL:  "https://status.zilliz.com/api/v2/summary.json",
		},
		{
			ID:          "digitalocean",
			Aliases:     []string{"do"},
			Name:        "DigitalOcean",
			Description: "DigitalOcean service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.digitalocean.com/",
			APIURL:      "https://status.digitalocean.com/api",
			SummaryURL:  "https://status.digitalocean.com/api/v2/summary.json",
		},
		{
			ID:          "fly",
			Aliases:     []string{"fly.io", "flyio"},
			Name:        "Fly.io",
			Description: "Fly.io service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.flyio.net/",
			APIURL:      "https://status.flyio.net/api",
			SummaryURL:  "https://status.flyio.net/api/v2/summary.json",
		},
		{
			ID:          "netlify",
			Name:        "Netlify",
			Description: "Netlify service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://www.netlifystatus.com/",
			APIURL:      "https://www.netlifystatus.com/api",
			SummaryURL:  "https://www.netlifystatus.com/api/v2/summary.json",
		},
		{
			ID:          "render",
			Name:        "Render",
			Description: "Render service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.render.com/",
			APIURL:      "https://status.render.com/api",
			SummaryURL:  "https://status.render.com/api/v2/summary.json",
		},
		{
			ID:          "vercel",
			Aliases:     []string{"turborepo", "vercel-remote-cache"},
			Name:        "Vercel",
			Description: "Vercel service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://www.vercel-status.com/",
			APIURL:      "https://www.vercel-status.com/api",
			SummaryURL:  "https://www.vercel-status.com/api/v2/summary.json",
		},
		{
			ID:          "anthropic",
			Aliases:     []string{"claude"},
			Name:        "Anthropic",
			Description: "Anthropic Claude service status",
			Category:    "AI",
			SourceURL:   "https://status.anthropic.com/",
			APIURL:      "https://status.anthropic.com/api",
			SummaryURL:  "https://status.anthropic.com/api/v2/summary.json",
		},
		{
			ID:          "openai",
			Aliases:     []string{"chatgpt"},
			Name:        "OpenAI",
			Description: "OpenAI service status",
			Category:    "AI",
			SourceURL:   "https://status.openai.com/",
			APIURL:      "https://status.openai.com/api/v2/summary.json",
			SummaryURL:  "https://status.openai.com/api/v2/summary.json",
		},
		{
			ID:          "bigeye",
			Name:        "Bigeye",
			Description: "Bigeye service status",
			Category:    "Observability",
			SourceURL:   "https://status.bigeye.com/",
			APIURL:      "https://status.bigeye.com/api",
			SummaryURL:  "https://status.bigeye.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-us1",
			Aliases:     []string{"datadog"},
			Name:        "Datadog US1",
			Description: "Datadog US1 service status",
			Category:    "Observability",
			SourceURL:   "https://status.datadoghq.com/",
			APIURL:      "https://status.datadoghq.com/api",
			SummaryURL:  "https://status.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-eu",
			Aliases:     []string{"ddog-eu"},
			Name:        "Datadog EU",
			Description: "Datadog EU service status",
			Category:    "Observability",
			SourceURL:   "https://status.datadoghq.eu/",
			APIURL:      "https://status.datadoghq.eu/api",
			SummaryURL:  "https://status.datadoghq.eu/api/v2/summary.json",
		},
		{
			ID:          "datadog-us5",
			Aliases:     []string{"ddog-us5"},
			Name:        "Datadog US5",
			Description: "Datadog US5 service status",
			Category:    "Observability",
			SourceURL:   "https://status.us5.datadoghq.com/",
			APIURL:      "https://status.us5.datadoghq.com/api",
			SummaryURL:  "https://status.us5.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-ap1",
			Aliases:     []string{"ddog-ap1"},
			Name:        "Datadog AP1",
			Description: "Datadog AP1 service status",
			Category:    "Observability",
			SourceURL:   "https://status.ap1.datadoghq.com/",
			APIURL:      "https://status.ap1.datadoghq.com/api",
			SummaryURL:  "https://status.ap1.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-ap2",
			Aliases:     []string{"ddog-ap2"},
			Name:        "Datadog AP2",
			Description: "Datadog AP2 service status",
			Category:    "Observability",
			SourceURL:   "https://status.ap2.datadoghq.com/",
			APIURL:      "https://status.ap2.datadoghq.com/api",
			SummaryURL:  "https://status.ap2.datadoghq.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-govcloud",
			Aliases:     []string{"datadog-gov", "ddog-gov", "ddog-govcloud"},
			Name:        "Datadog GovCloud",
			Description: "Datadog GovCloud service status",
			Category:    "Observability",
			SourceURL:   "https://status.ddog-gov.com/",
			APIURL:      "https://status.ddog-gov.com/api",
			SummaryURL:  "https://status.ddog-gov.com/api/v2/summary.json",
		},
		{
			ID:          "datadog-us2-gov",
			Aliases:     []string{"ddog-us2-gov", "datadog-us2-fed", "ddog-us2-fed"},
			Name:        "Datadog US2 Gov",
			Description: "Datadog US2 Gov service status",
			Category:    "Observability",
			SourceURL:   "https://status.us2.ddog-gov.com/",
			APIURL:      "https://status.us2.ddog-gov.com/api",
			SummaryURL:  "https://status.us2.ddog-gov.com/api/v2/summary.json",
		},
		{
			ID:          "new-relic",
			Aliases:     []string{"newrelic"},
			Name:        "New Relic",
			Description: "New Relic service status",
			Category:    "Observability",
			SourceURL:   "https://status.newrelic.com/",
			APIURL:      "https://status.newrelic.com/api",
			SummaryURL:  "https://status.newrelic.com/api/v2/summary.json",
		},
		{
			ID:          "sentry",
			Name:        "Sentry",
			Description: "Sentry service status",
			Category:    "Observability",
			SourceURL:   "https://status.sentry.io/",
			APIURL:      "https://status.sentry.io/api",
			SummaryURL:  "https://status.sentry.io/api/v2/summary.json",
		},
		{
			ID:          "twilio",
			Name:        "Twilio",
			Description: "Twilio service status",
			Category:    "Communication",
			SourceURL:   "https://status.twilio.com/",
			APIURL:      "https://status.twilio.com/api",
			SummaryURL:  "https://status.twilio.com/api/v2/summary.json",
		},
		{
			ID:          "1password",
			Aliases:     []string{"onepassword"},
			Name:        "1Password",
			Description: "1Password service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.1password.com/",
			APIURL:      "https://status.1password.com/api",
			SummaryURL:  "https://status.1password.com/api/v2/summary.json",
		},
		{
			ID:          "ably",
			Name:        "Ably",
			Description: "Ably service status",
			Category:    "Communication",
			SourceURL:   "https://status.ably.com/",
			APIURL:      "https://status.ably.com/api",
			SummaryURL:  "https://status.ably.com/api/v2/summary.json",
		},
		{
			ID:          "airtable",
			Name:        "Airtable",
			Description: "Airtable service status",
			Category:    "Collaboration",
			SourceURL:   "https://status.airtable.com/",
			APIURL:      "https://status.airtable.com/api",
			SummaryURL:  "https://status.airtable.com/api/v2/summary.json",
		},
		{
			ID:          "akeyless",
			Name:        "Akeyless",
			Description: "Akeyless service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.akeyless.io/",
			APIURL:      "https://status.akeyless.io/api",
			SummaryURL:  "https://status.akeyless.io/api/v2/summary.json",
		},
		{
			ID:          "amplitude",
			Name:        "Amplitude",
			Description: "Amplitude service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.amplitude.com/",
			APIURL:      "https://status.amplitude.com/api",
			SummaryURL:  "https://status.amplitude.com/api/v2/summary.json",
		},
		{
			ID:          "apigee",
			Name:        "Apigee",
			Description: "Apigee service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.apigee.com/",
			APIURL:      "https://status.apigee.com/api",
			SummaryURL:  "https://status.apigee.com/api/v2/summary.json",
		},
		{
			ID:          "axiom",
			Name:        "Axiom",
			Description: "Axiom service status",
			Category:    "Observability",
			SourceURL:   "https://status.axiom.co/",
			APIURL:      "https://status.axiom.co/api",
			SummaryURL:  "https://status.axiom.co/api/v2/summary.json",
		},
		{
			ID:          "baseten",
			Name:        "Baseten",
			Description: "Baseten service status",
			Category:    "AI",
			SourceURL:   "https://status.baseten.co/",
			APIURL:      "https://status.baseten.co/api",
			SummaryURL:  "https://status.baseten.co/api/v2/summary.json",
		},
		{
			ID:          "bitrise",
			Name:        "Bitrise",
			Description: "Bitrise service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.bitrise.io/",
			APIURL:      "https://status.bitrise.io/api",
			SummaryURL:  "https://status.bitrise.io/api/v2/summary.json",
		},
		{
			ID:          "braze",
			Name:        "Braze",
			Description: "Braze service status",
			Category:    "Communication",
			SourceURL:   "https://status.braze.com/",
			APIURL:      "https://status.braze.com/api",
			SummaryURL:  "https://status.braze.com/api/v2/summary.json",
		},
		{
			ID:          "bugsnag",
			Name:        "Bugsnag",
			Description: "Bugsnag service status",
			Category:    "Observability",
			SourceURL:   "https://status.bugsnag.com/",
			APIURL:      "https://status.bugsnag.com/api",
			SummaryURL:  "https://status.bugsnag.com/api/v2/summary.json",
		},
		{
			ID:          "census",
			Name:        "Census",
			Description: "Census service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.getcensus.com/",
			APIURL:      "https://status.getcensus.com/api",
			SummaryURL:  "https://status.getcensus.com/api/v2/summary.json",
		},
		{
			ID:          "chargebee",
			Name:        "Chargebee",
			Description: "Chargebee service status",
			Category:    "Payments & Billing",
			SourceURL:   "https://status.chargebee.com/",
			APIURL:      "https://status.chargebee.com/api",
			SummaryURL:  "https://status.chargebee.com/api/v2/summary.json",
		},
		{
			ID:          "circleci",
			Aliases:     []string{"circle-ci"},
			Name:        "CircleCI",
			Description: "CircleCI service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.circleci.com/",
			APIURL:      "https://status.circleci.com/api",
			SummaryURL:  "https://status.circleci.com/api/v2/summary.json",
		},
		{
			ID:          "clerk",
			Name:        "Clerk",
			Description: "Clerk service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.clerk.com/",
			APIURL:      "https://status.clerk.com/api",
			SummaryURL:  "https://status.clerk.com/api/v2/summary.json",
		},
		{
			ID:          "cloudsmith",
			Name:        "Cloudsmith",
			Description: "Cloudsmith service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.cloudsmith.com/",
			APIURL:      "https://status.cloudsmith.com/api",
			SummaryURL:  "https://status.cloudsmith.com/api/v2/summary.json",
		},
		{
			ID:          "coda",
			Name:        "Coda",
			Description: "Coda service status",
			Category:    "Collaboration",
			SourceURL:   "https://status.coda.io/",
			APIURL:      "https://status.coda.io/api",
			SummaryURL:  "https://status.coda.io/api/v2/summary.json",
		},
		{
			ID:          "codefresh",
			Name:        "Codefresh",
			Description: "Codefresh service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.codefresh.io/",
			APIURL:      "https://status.codefresh.io/api",
			SummaryURL:  "https://status.codefresh.io/api/v2/summary.json",
		},
		{
			ID:          "cohere",
			Name:        "Cohere",
			Description: "Cohere service status",
			Category:    "AI",
			SourceURL:   "https://status.cohere.com/",
			APIURL:      "https://status.cohere.com/api",
			SummaryURL:  "https://status.cohere.com/api/v2/summary.json",
		},
		{
			ID:          "convex",
			Name:        "Convex",
			Description: "Convex service status",
			Category:    "Databases",
			SourceURL:   "https://status.convex.dev/",
			APIURL:      "https://status.convex.dev/api",
			SummaryURL:  "https://status.convex.dev/api/v2/summary.json",
		},
		{
			ID:          "coralogix",
			Name:        "Coralogix",
			Description: "Coralogix service status",
			Category:    "Observability",
			SourceURL:   "https://status.coralogix.com/",
			APIURL:      "https://status.coralogix.com/api",
			SummaryURL:  "https://status.coralogix.com/api/v2/summary.json",
		},
		{
			ID:          "courier",
			Name:        "Courier",
			Description: "Courier service status",
			Category:    "Communication",
			SourceURL:   "https://status.courier.com/",
			APIURL:      "https://status.courier.com/api",
			SummaryURL:  "https://status.courier.com/api/v2/summary.json",
		},
		{
			ID:          "crates-io",
			Aliases:     []string{"crates", "rust-crates"},
			Name:        "crates.io",
			Description: "crates.io service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.crates.io/",
			APIURL:      "https://status.crates.io/api",
			SummaryURL:  "https://status.crates.io/api/v2/summary.json",
		},
		{
			ID:          "depot",
			Aliases:     []string{"depot-dev"},
			Name:        "Depot",
			Description: "Depot service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.depot.dev/",
			APIURL:      "https://status.depot.dev/api",
			SummaryURL:  "https://status.depot.dev/api/v2/summary.json",
		},
		{
			ID:          "discord",
			Name:        "Discord",
			Description: "Discord service status",
			Category:    "Communication",
			SourceURL:   "https://discordstatus.com/",
			APIURL:      "https://discordstatus.com/api",
			SummaryURL:  "https://discordstatus.com/api/v2/summary.json",
		},
		{
			ID:          "doppler",
			Name:        "Doppler",
			Description: "Doppler service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.doppler.com/",
			APIURL:      "https://status.doppler.com/api",
			SummaryURL:  "https://status.doppler.com/api/v2/summary.json",
		},
		{
			ID:          "drata",
			Name:        "Drata",
			Description: "Drata service status",
			Category:    "Security",
			SourceURL:   "https://status.drata.com/",
			APIURL:      "https://status.drata.com/api",
			SummaryURL:  "https://status.drata.com/api/v2/summary.json",
		},
		{
			ID:          "expo",
			Aliases:     []string{"eas"},
			Name:        "Expo",
			Description: "Expo service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.expo.dev/",
			APIURL:      "https://status.expo.dev/api",
			SummaryURL:  "https://status.expo.dev/api/v2/summary.json",
		},
		{
			ID:          "figma",
			Name:        "Figma",
			Description: "Figma service status",
			Category:    "Collaboration",
			SourceURL:   "https://status.figma.com/",
			APIURL:      "https://status.figma.com/api",
			SummaryURL:  "https://status.figma.com/api/v2/summary.json",
		},
		{
			ID:          "fullstory",
			Name:        "Fullstory",
			Description: "Fullstory service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.fullstory.com/",
			APIURL:      "https://status.fullstory.com/api",
			SummaryURL:  "https://status.fullstory.com/api/v2/summary.json",
		},
		{
			ID:          "gitguardian",
			Name:        "GitGuardian",
			Description: "GitGuardian service status",
			Category:    "Security",
			SourceURL:   "https://status.gitguardian.com/",
			APIURL:      "https://status.gitguardian.com/api",
			SummaryURL:  "https://status.gitguardian.com/api/v2/summary.json",
		},
		{
			ID:          "gocardless",
			Aliases:     []string{"go-cardless"},
			Name:        "GoCardless",
			Description: "GoCardless service status",
			Category:    "Payments & Billing",
			SourceURL:   "https://gocardless-status.com/",
			APIURL:      "https://gocardless-status.com/api",
			SummaryURL:  "https://gocardless-status.com/api/v2/summary.json",
		},
		{
			ID:          "grafana-cloud",
			Aliases:     []string{"grafana"},
			Name:        "Grafana Cloud",
			Description: "Grafana Cloud service status",
			Category:    "Observability",
			SourceURL:   "https://status.grafana.com/",
			APIURL:      "https://status.grafana.com/api",
			SummaryURL:  "https://status.grafana.com/api/v2/summary.json",
		},
		{
			ID:          "harness",
			Name:        "Harness",
			Description: "Harness service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.harness.io/",
			APIURL:      "https://status.harness.io/api",
			SummaryURL:  "https://status.harness.io/api/v2/summary.json",
		},
		{
			ID:          "heap",
			Name:        "Heap",
			Description: "Heap service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.heap.io/",
			APIURL:      "https://status.heap.io/api",
			SummaryURL:  "https://status.heap.io/api/v2/summary.json",
		},
		{
			ID:          "honeycomb",
			Name:        "Honeycomb",
			Description: "Honeycomb service status",
			Category:    "Observability",
			SourceURL:   "https://status.honeycomb.io/",
			APIURL:      "https://status.honeycomb.io/api",
			SummaryURL:  "https://status.honeycomb.io/api/v2/summary.json",
		},
		{
			ID:          "incident-io",
			Aliases:     []string{"incident"},
			Name:        "incident.io",
			Description: "incident.io service status",
			Category:    "Incident Management",
			SourceURL:   "https://status.incident.io/",
			APIURL:      "https://status.incident.io/api",
			SummaryURL:  "https://status.incident.io/api/v2/summary.json",
		},
		{
			ID:          "infisical",
			Name:        "Infisical",
			Description: "Infisical service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.infisical.com/",
			APIURL:      "https://status.infisical.com/api",
			SummaryURL:  "https://status.infisical.com/api/v2/summary.json",
		},
		{
			ID:          "influxdb-cloud",
			Aliases:     []string{"influxdb"},
			Name:        "InfluxDB Cloud",
			Description: "InfluxDB Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.influxdata.com/",
			APIURL:      "https://status.influxdata.com/api",
			SummaryURL:  "https://status.influxdata.com/api/v2/summary.json",
		},
		{
			ID:          "inngest",
			Name:        "Inngest",
			Description: "Inngest service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.inngest.com/",
			APIURL:      "https://status.inngest.com/api",
			SummaryURL:  "https://status.inngest.com/api/v2/summary.json",
		},
		{
			ID:          "jfrog",
			Aliases:     []string{"artifactory", "artifactory-cloud"},
			Name:        "JFrog Cloud",
			Description: "JFrog Cloud service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.jfrog.io/",
			APIURL:      "https://status.jfrog.io/api",
			SummaryURL:  "https://status.jfrog.io/api/v2/summary.json",
		},
		{
			ID:          "kong",
			Aliases:     []string{"kong-konnect"},
			Name:        "Kong",
			Description: "Kong service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.konghq.com/",
			APIURL:      "https://status.konghq.com/api",
			SummaryURL:  "https://status.konghq.com/api/v2/summary.json",
		},
		{
			ID:          "launchdarkly",
			Name:        "LaunchDarkly",
			Description: "LaunchDarkly service status",
			Category:    "Feature Flags",
			SourceURL:   "https://status.launchdarkly.com/",
			APIURL:      "https://status.launchdarkly.com/api",
			SummaryURL:  "https://status.launchdarkly.com/api/v2/summary.json",
		},
		{
			ID:          "logzio",
			Aliases:     []string{"logz.io"},
			Name:        "Logz.io",
			Description: "Logz.io service status",
			Category:    "Observability",
			SourceURL:   "https://status.logz.io/",
			APIURL:      "https://status.logz.io/api",
			SummaryURL:  "https://status.logz.io/api/v2/summary.json",
		},
		{
			ID:          "mailgun",
			Name:        "Mailgun",
			Description: "Mailgun service status",
			Category:    "Communication",
			SourceURL:   "https://status.mailgun.com/",
			APIURL:      "https://status.mailgun.com/api",
			SummaryURL:  "https://status.mailgun.com/api/v2/summary.json",
		},
		{
			ID:          "maven-central",
			Aliases:     []string{"maven"},
			Name:        "Maven Central",
			Description: "Maven Central service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.maven.org/",
			APIURL:      "https://status.maven.org/api",
			SummaryURL:  "https://status.maven.org/api/v2/summary.json",
		},
		{
			ID:          "mend",
			Name:        "Mend",
			Description: "Mend service status",
			Category:    "Security",
			SourceURL:   "https://status.mend.io/",
			APIURL:      "https://status.mend.io/api",
			SummaryURL:  "https://status.mend.io/api/v2/summary.json",
		},
		{
			ID:          "mintlify",
			Name:        "Mintlify",
			Description: "Mintlify service status",
			Category:    "Documentation",
			SourceURL:   "https://status.mintlify.com/",
			APIURL:      "https://status.mintlify.com/api",
			SummaryURL:  "https://status.mintlify.com/api/v2/summary.json",
		},
		{
			ID:          "miro",
			Name:        "Miro",
			Description: "Miro service status",
			Category:    "Collaboration",
			SourceURL:   "https://status.miro.com/",
			APIURL:      "https://status.miro.com/api",
			SummaryURL:  "https://status.miro.com/api/v2/summary.json",
		},
		{
			ID:          "mixpanel",
			Name:        "Mixpanel",
			Description: "Mixpanel service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.mixpanel.com/",
			APIURL:      "https://status.mixpanel.com/api",
			SummaryURL:  "https://status.mixpanel.com/api/v2/summary.json",
		},
		{
			ID:          "npm",
			Name:        "npm",
			Description: "npm service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.npmjs.org/",
			APIURL:      "https://status.npmjs.org/api",
			SummaryURL:  "https://status.npmjs.org/api/v2/summary.json",
		},
		{
			ID:          "nx-cloud",
			Aliases:     []string{"nx"},
			Name:        "Nx Cloud",
			Description: "Nx Cloud service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.nx.app/",
			APIURL:      "https://status.nx.app/api",
			SummaryURL:  "https://status.nx.app/api/v2/summary.json",
		},
		{
			ID:          "onesignal",
			Aliases:     []string{"one-signal"},
			Name:        "OneSignal",
			Description: "OneSignal service status",
			Category:    "Communication",
			SourceURL:   "https://status.onesignal.com/",
			APIURL:      "https://status.onesignal.com/api",
			SummaryURL:  "https://status.onesignal.com/api/v2/summary.json",
		},
		{
			ID:          "opsgenie",
			Name:        "Opsgenie",
			Description: "Opsgenie service status",
			Category:    "Incident Management",
			SourceURL:   "https://status.opsgenie.com/",
			APIURL:      "https://status.opsgenie.com/api",
			SummaryURL:  "https://status.opsgenie.com/api/v2/summary.json",
		},
		{
			ID:          "pendo",
			Name:        "Pendo",
			Description: "Pendo service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.pendo.io/",
			APIURL:      "https://status.pendo.io/api",
			SummaryURL:  "https://status.pendo.io/api/v2/summary.json",
		},
		{
			ID:          "postman",
			Name:        "Postman",
			Description: "Postman service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.postman.com/",
			APIURL:      "https://status.postman.com/api",
			SummaryURL:  "https://status.postman.com/api/v2/summary.json",
		},
		{
			ID:          "pubnub",
			Name:        "PubNub",
			Description: "PubNub service status",
			Category:    "Communication",
			SourceURL:   "https://status.pubnub.com/",
			APIURL:      "https://status.pubnub.com/api",
			SummaryURL:  "https://status.pubnub.com/api/v2/summary.json",
		},
		{
			ID:          "pusher",
			Name:        "Pusher",
			Description: "Pusher service status",
			Category:    "Communication",
			SourceURL:   "https://status.pusher.com/",
			APIURL:      "https://status.pusher.com/api",
			SummaryURL:  "https://status.pusher.com/api/v2/summary.json",
		},
		{
			ID:          "pypi",
			Aliases:     []string{"python"},
			Name:        "PyPI",
			Description: "PyPI service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.python.org/",
			APIURL:      "https://status.python.org/api",
			SummaryURL:  "https://status.python.org/api/v2/summary.json",
		},
		{
			ID:          "quay",
			Aliases:     []string{"quay.io"},
			Name:        "Quay.io",
			Description: "Quay.io service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.quay.io/",
			APIURL:      "https://status.quay.io/api",
			SummaryURL:  "https://status.quay.io/api/v2/summary.json",
		},
		{
			ID:          "readme",
			Name:        "ReadMe",
			Description: "ReadMe service status",
			Category:    "Documentation",
			SourceURL:   "https://status.readme.com/",
			APIURL:      "https://status.readme.com/api",
			SummaryURL:  "https://status.readme.com/api/v2/summary.json",
		},
		{
			ID:          "replicate",
			Name:        "Replicate",
			Description: "Replicate service status",
			Category:    "AI",
			SourceURL:   "https://status.replicate.com/",
			APIURL:      "https://status.replicate.com/api",
			SummaryURL:  "https://status.replicate.com/api/v2/summary.json",
		},
		{
			ID:          "revenuecat",
			Name:        "RevenueCat",
			Description: "RevenueCat service status",
			Category:    "Payments & Billing",
			SourceURL:   "https://status.revenuecat.com/",
			APIURL:      "https://status.revenuecat.com/api",
			SummaryURL:  "https://status.revenuecat.com/api/v2/summary.json",
		},
		{
			ID:          "rollbar",
			Name:        "Rollbar",
			Description: "Rollbar service status",
			Category:    "Observability",
			SourceURL:   "https://status.rollbar.com/",
			APIURL:      "https://status.rollbar.com/api",
			SummaryURL:  "https://status.rollbar.com/api/v2/summary.json",
		},
		{
			ID:          "rubygems",
			Aliases:     []string{"ruby-gems"},
			Name:        "RubyGems",
			Description: "RubyGems service status",
			Category:    "Package Registries",
			SourceURL:   "https://status.rubygems.org/",
			APIURL:      "https://status.rubygems.org/api",
			SummaryURL:  "https://status.rubygems.org/api/v2/summary.json",
		},
		{
			ID:          "rudderstack",
			Name:        "RudderStack",
			Description: "RudderStack service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.rudderstack.com/",
			APIURL:      "https://status.rudderstack.com/api",
			SummaryURL:  "https://status.rudderstack.com/api/v2/summary.json",
		},
		{
			ID:          "segment",
			Name:        "Segment",
			Description: "Segment service status",
			Category:    "Product Analytics",
			SourceURL:   "https://status.segment.com/",
			APIURL:      "https://status.segment.com/api",
			SummaryURL:  "https://status.segment.com/api/v2/summary.json",
		},
		{
			ID:          "semaphore",
			Aliases:     []string{"semaphoreci"},
			Name:        "Semaphore",
			Description: "Semaphore service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.semaphoreci.com/",
			APIURL:      "https://status.semaphoreci.com/api",
			SummaryURL:  "https://status.semaphoreci.com/api/v2/summary.json",
		},
		{
			ID:          "semgrep",
			Name:        "Semgrep",
			Description: "Semgrep service status",
			Category:    "Security",
			SourceURL:   "https://status.semgrep.dev/",
			APIURL:      "https://status.semgrep.dev/api",
			SummaryURL:  "https://status.semgrep.dev/api/v2/summary.json",
		},
		{
			ID:          "sendgrid",
			Name:        "SendGrid",
			Description: "SendGrid service status",
			Category:    "Communication",
			SourceURL:   "https://status.sendgrid.com/",
			APIURL:      "https://status.sendgrid.com/api",
			SummaryURL:  "https://status.sendgrid.com/api/v2/summary.json",
		},
		{
			ID:          "shortcut",
			Name:        "Shortcut",
			Description: "Shortcut service status",
			Category:    "Project Management",
			SourceURL:   "https://status.shortcut.com/",
			APIURL:      "https://status.shortcut.com/api",
			SummaryURL:  "https://status.shortcut.com/api/v2/summary.json",
		},
		{
			ID:          "snyk",
			Name:        "Snyk",
			Description: "Snyk service status",
			Category:    "Security",
			SourceURL:   "https://status.snyk.io/",
			APIURL:      "https://status.snyk.io/api",
			SummaryURL:  "https://status.snyk.io/api/v2/summary.json",
		},
		{
			ID:          "sparkpost",
			Name:        "SparkPost",
			Description: "SparkPost service status",
			Category:    "Communication",
			SourceURL:   "https://status.sparkpost.com/",
			APIURL:      "https://status.sparkpost.com/api",
			SummaryURL:  "https://status.sparkpost.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-cloud",
			Aliases:     []string{"splunkcloud"},
			Name:        "Splunk Cloud Platform",
			Description: "Splunk Cloud Platform service status",
			Category:    "Cloud & Hosting",
			SourceURL:   "https://status.splunkcloud.com/",
			APIURL:      "https://status.splunkcloud.com/api",
			SummaryURL:  "https://status.splunkcloud.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-au0",
			Aliases:     []string{"signalfx-au0"},
			Name:        "Splunk Observability Cloud AU0",
			Description: "Splunk Observability Cloud AU0 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.au0.signalfx.com/",
			APIURL:      "https://status.au0.signalfx.com/api",
			SummaryURL:  "https://status.au0.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-eu0",
			Aliases:     []string{"signalfx-eu0"},
			Name:        "Splunk Observability Cloud EU0",
			Description: "Splunk Observability Cloud EU0 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.eu0.signalfx.com/",
			APIURL:      "https://status.eu0.signalfx.com/api",
			SummaryURL:  "https://status.eu0.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-eu2",
			Aliases:     []string{"signalfx-eu2"},
			Name:        "Splunk Observability Cloud EU2",
			Description: "Splunk Observability Cloud EU2 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.eu2.signalfx.com/",
			APIURL:      "https://status.eu2.signalfx.com/api",
			SummaryURL:  "https://status.eu2.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-jp0",
			Aliases:     []string{"signalfx-jp0"},
			Name:        "Splunk Observability Cloud JP0",
			Description: "Splunk Observability Cloud JP0 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.jp0.signalfx.com/",
			APIURL:      "https://status.jp0.signalfx.com/api",
			SummaryURL:  "https://status.jp0.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-sg0",
			Aliases:     []string{"signalfx-sg0"},
			Name:        "Splunk Observability Cloud SG0",
			Description: "Splunk Observability Cloud SG0 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.sg0.signalfx.com/",
			APIURL:      "https://status.sg0.signalfx.com/api",
			SummaryURL:  "https://status.sg0.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-us0",
			Aliases:     []string{"signalfx", "signalfx-us0"},
			Name:        "Splunk Observability Cloud US0",
			Description: "Splunk Observability Cloud US0 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.us0.signalfx.com/",
			APIURL:      "https://status.us0.signalfx.com/api",
			SummaryURL:  "https://status.us0.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-us1",
			Aliases:     []string{"signalfx-us1"},
			Name:        "Splunk Observability Cloud US1",
			Description: "Splunk Observability Cloud US1 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.us1.signalfx.com/",
			APIURL:      "https://status.us1.signalfx.com/api",
			SummaryURL:  "https://status.us1.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-observability-us2",
			Aliases:     []string{"signalfx-us2"},
			Name:        "Splunk Observability Cloud US2",
			Description: "Splunk Observability Cloud US2 regional status",
			Category:    "Observability",
			SourceURL:   "https://status.us2.signalfx.com/",
			APIURL:      "https://status.us2.signalfx.com/api",
			SummaryURL:  "https://status.us2.signalfx.com/api/v2/summary.json",
		},
		{
			ID:          "splunk-on-call",
			Aliases:     []string{"victorops"},
			Name:        "Splunk On-Call",
			Description: "Splunk On-Call service status",
			Category:    "Incident Management",
			SourceURL:   "https://status.victorops.com/",
			APIURL:      "https://status.victorops.com/api",
			SummaryURL:  "https://status.victorops.com/api/v2/summary.json",
		},
		{
			ID:          "square",
			Aliases:     []string{"squareup"},
			Name:        "Square",
			Description: "Square service status",
			Category:    "Payments & Billing",
			SourceURL:   "https://www.issquareup.com/",
			APIURL:      "https://www.issquareup.com/api",
			SummaryURL:  "https://www.issquareup.com/api/v2/summary.json",
		},
		{
			ID:          "statuscake",
			Name:        "StatusCake",
			Description: "StatusCake service status",
			Category:    "Observability",
			SourceURL:   "https://status.statuscake.com/",
			APIURL:      "https://status.statuscake.com/api",
			SummaryURL:  "https://status.statuscake.com/api/v2/summary.json",
		},
		{
			ID:          "stoplight",
			Name:        "Stoplight",
			Description: "Stoplight service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.stoplight.io/",
			APIURL:      "https://status.stoplight.io/api",
			SummaryURL:  "https://status.stoplight.io/api/v2/summary.json",
		},
		{
			ID:          "stream",
			Aliases:     []string{"getstream"},
			Name:        "Stream",
			Description: "Stream service status",
			Category:    "Communication",
			SourceURL:   "https://status.getstream.io/",
			APIURL:      "https://status.getstream.io/api",
			SummaryURL:  "https://status.getstream.io/api/v2/summary.json",
		},
		{
			ID:          "svix",
			Name:        "Svix",
			Description: "Svix service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.svix.com/",
			APIURL:      "https://status.svix.com/api",
			SummaryURL:  "https://status.svix.com/api/v2/summary.json",
		},
		{
			ID:          "tailscale",
			Name:        "Tailscale",
			Description: "Tailscale service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.tailscale.com/",
			APIURL:      "https://status.tailscale.com/api",
			SummaryURL:  "https://status.tailscale.com/api/v2/summary.json",
		},
		{
			ID:          "teleport-cloud",
			Aliases:     []string{"teleport"},
			Name:        "Teleport Cloud",
			Description: "Teleport Cloud service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.teleport.sh/",
			APIURL:      "https://status.teleport.sh/api",
			SummaryURL:  "https://status.teleport.sh/api/v2/summary.json",
		},
		{
			ID:          "temporal-cloud",
			Aliases:     []string{"temporal"},
			Name:        "Temporal Cloud",
			Description: "Temporal Cloud service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.temporal.io/",
			APIURL:      "https://status.temporal.io/api",
			SummaryURL:  "https://status.temporal.io/api/v2/summary.json",
		},
		{
			ID:          "travis-ci",
			Aliases:     []string{"travis"},
			Name:        "Travis CI",
			Description: "Travis CI service status",
			Category:    "CI/CD",
			SourceURL:   "https://www.traviscistatus.com/",
			APIURL:      "https://www.traviscistatus.com/api",
			SummaryURL:  "https://www.traviscistatus.com/api/v2/summary.json",
		},
		{
			ID:          "tyk",
			Aliases:     []string{"tyk-cloud"},
			Name:        "Tyk Cloud",
			Description: "Tyk Cloud service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.tyk.io/",
			APIURL:      "https://status.tyk.io/api",
			SummaryURL:  "https://status.tyk.io/api/v2/summary.json",
		},
		{
			ID:          "upstash",
			Name:        "Upstash",
			Description: "Upstash service status",
			Category:    "Databases",
			SourceURL:   "https://status.upstash.com/",
			APIURL:      "https://status.upstash.com/api",
			SummaryURL:  "https://status.upstash.com/api/v2/summary.json",
		},
		{
			ID:          "vanta",
			Name:        "Vanta",
			Description: "Vanta service status",
			Category:    "Security",
			SourceURL:   "https://status.vanta.com/",
			APIURL:      "https://status.vanta.com/api",
			SummaryURL:  "https://status.vanta.com/api/v2/summary.json",
		},
		{
			ID:          "veracode",
			Name:        "Veracode",
			Description: "Veracode service status",
			Category:    "Security",
			SourceURL:   "https://status.veracode.com/",
			APIURL:      "https://status.veracode.com/api",
			SummaryURL:  "https://status.veracode.com/api/v2/summary.json",
		},
		{
			ID:          "wiz",
			Name:        "Wiz",
			Description: "Wiz service status",
			Category:    "Security",
			SourceURL:   "https://status.wiz.io/",
			APIURL:      "https://status.wiz.io/api",
			SummaryURL:  "https://status.wiz.io/api/v2/summary.json",
		},
		{
			ID:          "workos",
			Name:        "WorkOS",
			Description: "WorkOS service status",
			Category:    "Identity & Security",
			SourceURL:   "https://status.workos.com/",
			APIURL:      "https://status.workos.com/api",
			SummaryURL:  "https://status.workos.com/api/v2/summary.json",
		},
		{
			ID:          "zoom",
			Name:        "Zoom",
			Description: "Zoom service status",
			Category:    "Communication",
			SourceURL:   "https://status.zoom.us/",
			APIURL:      "https://status.zoom.us/api",
			SummaryURL:  "https://status.zoom.us/api/v2/summary.json",
		},
		{
			ID:          "zuora",
			Name:        "Zuora",
			Description: "Zuora service status",
			Category:    "Payments & Billing",
			SourceURL:   "https://trust.zuora.com/",
			APIURL:      "https://trust.zuora.com/api",
			SummaryURL:  "https://trust.zuora.com/api/v2/summary.json",
		},
		{
			ID:          "airbyte",
			Name:        "Airbyte",
			Description: "Airbyte service status",
			Category:    "Data Integration",
			SourceURL:   "https://status.airbyte.com/",
			APIURL:      "https://status.airbyte.com/api",
			SummaryURL:  "https://status.airbyte.com/api/v2/summary.json",
		},
		{
			ID:          "codemagic",
			Name:        "Codemagic",
			Description: "Codemagic service status",
			Category:    "CI/CD",
			SourceURL:   "https://status.codemagic.io/",
			APIURL:      "https://status.codemagic.io/api",
			SummaryURL:  "https://status.codemagic.io/api/v2/summary.json",
		},
		{
			ID:          "cursor",
			Name:        "Cursor",
			Description: "Cursor service status",
			Category:    "AI",
			SourceURL:   "https://status.cursor.com/",
			APIURL:      "https://status.cursor.com/api",
			SummaryURL:  "https://status.cursor.com/api/v2/summary.json",
		},
		{
			ID:          "flagsmith",
			Name:        "Flagsmith",
			Description: "Flagsmith service status",
			Category:    "Feature Flags",
			SourceURL:   "https://status.flagsmith.com/",
			APIURL:      "https://status.flagsmith.com/api",
			SummaryURL:  "https://status.flagsmith.com/api/v2/summary.json",
		},
		{
			ID:          "keeper",
			Name:        "Keeper",
			Description: "Keeper service status",
			Category:    "Identity & Security",
			SourceURL:   "https://statuspage.keeper.io/",
			APIURL:      "https://statuspage.keeper.io/api",
			SummaryURL:  "https://statuspage.keeper.io/api/v2/summary.json",
		},
		{
			ID:          "lovable",
			Name:        "Lovable",
			Description: "Lovable service status",
			Category:    "AI",
			SourceURL:   "https://status.lovable.dev/",
			APIURL:      "https://status.lovable.dev/api",
			SummaryURL:  "https://status.lovable.dev/api/v2/summary.json",
		},
		{
			ID:          "notion",
			Name:        "Notion",
			Description: "Notion service status",
			Category:    "Collaboration",
			SourceURL:   "https://www.notion-status.com/",
			APIURL:      "https://www.notion-status.com/api",
			SummaryURL:  "https://www.notion-status.com/api/v2/summary.json",
		},
		{
			ID:          "optimizely",
			Name:        "Optimizely",
			Description: "Optimizely service status",
			Category:    "Feature Flags",
			SourceURL:   "https://status.optimizely.com/",
			APIURL:      "https://status.optimizely.com/api",
			SummaryURL:  "https://status.optimizely.com/api/v2/summary.json",
		},
		{
			ID:          "perplexity",
			Name:        "Perplexity",
			Description: "Perplexity service status",
			Category:    "AI",
			SourceURL:   "https://status.perplexity.com/",
			APIURL:      "https://status.perplexity.com/api",
			SummaryURL:  "https://status.perplexity.com/api/v2/summary.json",
		},
		{
			ID:          "proton",
			Name:        "Proton",
			Description: "Proton service status",
			Category:    "Collaboration",
			SourceURL:   "https://status.proton.me/",
			APIURL:      "https://status.proton.me/api",
			SummaryURL:  "https://status.proton.me/api/v2/summary.json",
		},
		{
			ID:          "swagger",
			Aliases:     []string{"smartbear-swagger"},
			Name:        "Swagger",
			Description: "Swagger service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://swagger.status.smartbear.com/",
			APIURL:      "https://swagger.status.smartbear.com/api",
			SummaryURL:  "https://swagger.status.smartbear.com/api/v2/summary.json",
		},
		{
			ID:          "tidb-cloud",
			Aliases:     []string{"tidb"},
			Name:        "TiDB Cloud",
			Description: "TiDB Cloud service status",
			Category:    "Databases",
			SourceURL:   "https://status.tidbcloud.com/",
			APIURL:      "https://status.tidbcloud.com/api",
			SummaryURL:  "https://status.tidbcloud.com/api/v2/summary.json",
		},
		{
			ID:          "tinybird",
			Name:        "Tinybird",
			Description: "Tinybird service status",
			Category:    "Data Platforms",
			SourceURL:   "https://status.tinybird.co/",
			APIURL:      "https://status.tinybird.co/api",
			SummaryURL:  "https://status.tinybird.co/api/v2/summary.json",
		},
		{
			ID:          "windsurf",
			Name:        "Windsurf",
			Description: "Windsurf service status",
			Category:    "AI",
			SourceURL:   "https://status.windsurf.com/",
			APIURL:      "https://status.windsurf.com/api",
			SummaryURL:  "https://status.windsurf.com/api/v2/summary.json",
		},
		{
			ID:          "zuplo",
			Name:        "Zuplo",
			Description: "Zuplo service status",
			Category:    "API & Developer Tools",
			SourceURL:   "https://status.zuplo.com/",
			APIURL:      "https://status.zuplo.com/api",
			SummaryURL:  "https://status.zuplo.com/api/v2/summary.json",
		},
	}

	registrations := make([]registration, 0, len(options))
	for _, option := range options {
		current := option
		provider := statuspage.NewProvider(client, current)
		registrations = append(registrations, registration{
			metadata: provider.Metadata(),
			factory: func() providers.Provider {
				return statuspage.NewProvider(client, current)
			},
		})
	}

	return registrations
}
